# Generated by Django 5.1.5 on 2025-05-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('NEW', 'New'), ('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
