# Generated by Django 5.1.5 on 2025-06-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('NEW', 'New'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=20),
        ),
    ]
