# Generated by Django 5.1.5 on 2025-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0003_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('NEW', 'New'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
