# Generated by Django 5.1.5 on 2026-01-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_auth', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('ACTIVE', 'Active'), ('NEW', 'New'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20),
        ),
    ]
