# Generated by Django 5.1.5 on 2026-01-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridge',
            options={},
        ),
    ]
