# Generated by Django 5.1.5 on 2025-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnh_model', '0004_remove_row_block_remove_box_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='fridgepartition',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
